##### Importando librería Numpy


In [4]:
import numpy as np

#### Creando una lista de 10 elementos

In [5]:
lista = list(range(1,11))
lista 

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

#### transformando la lista a un array

In [6]:
arreglo = np.array(lista)
arreglo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#### corroborando el tipo de objeto

In [7]:
type(arreglo) #LOS ARREGLOS SON DE UN SOLO TIPO

numpy.ndarray

#### corroborando el tipo de datos del arreglo

In [8]:
arreglo.dtype #indica el tipo de dato del arreglo: float, int, str, booleano
# INT 32 = ENTERO DE 32 BITS, INDICA LA LONGITUD

dtype('int32')

#### definiendo el array de int32 a float32

In [9]:
np.array(arreglo, dtype=np.float32)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32)

##### Sigue siendo un array de int32

In [10]:
arreglo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#### transformando el array de int32 a float32

In [ ]:
arreglo.astype(np.float32)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32)

#### También se puede crear un array de forma directa, sin tener que crear la lista primero

In [11]:
arreglonuevo = np.arange(1,11)
arreglonuevo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#### Array de 2 en 2 utilizando ARANGE

In [12]:
arreglonuevo2 = np.arange(1,11,2)
arreglonuevo2

array([1, 3, 5, 7, 9])

# ALGUNAS FUNCIONES DE NUMPY

#### obteniendo el promedio del arreglo


In [ ]:
promedio = np.mean(arreglo)
promedio

5.5

#### obteniendo la mediana del arreglo


In [ ]:
mediana = np.median(arreglo)
mediana

5.5

#### obteniendo la desviación estándar del arreglo


In [ ]:
desviacionestandar = np.std(arreglo)
desviacionestandar

2.8722813232690143

#### generando un arreglo de 10 elementos de solo unos


In [13]:
arreglo_de_unos = np.ones(10)
arreglo_de_unos

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### transformando el arreglo de 10 unos a int

In [14]:
arreglo_int_ones= arreglo_de_unos.astype(int)
arreglo_int_ones

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

#### generando un arreglo de 5 elementos de solo ceros

In [15]:
arreglo_de_ceros = np.zeros(5)
arreglo_de_ceros

array([0., 0., 0., 0., 0.])

### UTLIZANDO LA FUNCIÓN RANDOM

#### generando arreglo aleatorio de 5 elementos

In [16]:
arreglo_aleatorio = np.random.rand(5)
arreglo_aleatorio

array([0.52591987, 0.77495668, 0.46668887, 0.61811625, 0.82258337])

#### generando un arreglo aleatorio de 10 numeros enteros del 1 al 5

In [17]:
arreglo_aleatorio2 = np.random.randint(1,100,10) # rango del 1 al 100, 10 elementos
arreglo_aleatorio2 

array([10, 44, 62, 98, 33, 90, 90,  5, 76, 61])

#### generando una matriz aleatoria de 3x3

In [18]:
matriz = np.random.rand(3,3)
matriz

array([[0.05325188, 0.92121638, 0.78910796],
       [0.99896762, 0.00543534, 0.53679365],
       [0.88523961, 0.30760658, 0.81898094]])

#### generando un amatriz aleatoria de 10 numeros enteros del 1 al 100

In [19]:
matriz2 = np.random.randint(1,100,(10,10)) # rango del 1 al 100, parametros de 10x10 (filasxcolumnas) 
matriz2

array([[ 9, 53, 51, 58, 69, 56, 87, 93, 89, 13],
       [96, 24, 88,  7, 70, 62,  9, 50, 21, 30],
       [63, 37, 74, 12, 99, 41, 71, 35, 35, 21],
       [ 8, 48, 66, 56, 84, 29, 79, 35, 56, 78],
       [49, 19, 63, 83, 44,  7, 98, 53, 38, 26],
       [21, 18,  8, 75,  2, 10, 58, 61, 42, 76],
       [15, 74, 57, 18, 41, 13, 40, 83, 67, 36],
       [74, 41, 45, 67, 47, 96, 32, 55, 24, 66],
       [37, 86, 43, 66, 35, 91, 80, 96,  3, 61],
       [43,  8, 96, 82, 52, 58, 98, 53, 12, 54]])